SportEquipmentRent/Models/SportEquipment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportEquipmentRent.Models
{
    public class SportEquipment
    {
        public int Id { get; set; }
        [Display(Name = "Nazwa")]
        [StringLength(200, ErrorMessage = "Nazwa musi mieć maksymalnie 200 znaków")]
        public string Name { get; set; }
        [Display(Name = "Liczba wszystkich sztuk")]

        [Range(1, 1000, ErrorMessage = "Liczba sztuk musi być pomiędzy 1 a 1000")]
        public int Units { get; set; }
        public ICollection<Renting> Rentings { get; set; } = new List<Renting>();
        [Display(Name = "Liczba dostępnycgh sztuk")]
        public int AvaibleUnits()
        {
            int currentRents = Rentings.Where(x => x.End.Date >= DateTime.UtcNow.Date).Count();

            return Units - currentRents;
        }

    }
}

SportEquipmentRent/Controllers/RentingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportEquipmentRent.Data;
using SportEquipmentRent.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace SportEquipmentRent.Controllers
{
    [Authorize]

    public class RentingController : Controller
    {
        private readonly ApplicationDbContext _context;
        public string? CurrentUserId
        {
            get
            {
                return User.FindFirstValue(ClaimTypes.NameIdentifier);
            }
        }
        public RentingController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Renting.Include(x => x.User).Include(x => x.SportEquipment).Where(u => u.UserId == CurrentUserId || User.IsInRole("Admin") ).ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var renting = await _context.Renting
                .FirstOrDefaultAsync(m => m.Id == id);
            if (renting == null)
            {
                return NotFound();
            }
            if (renting.UserId != User.FindFirstValue(ClaimTypes.NameIdentifier) && !User.IsInRole("Admin"))
            {
                throw new Exception();
            }
            return View(renting);
        }
        public IActionResult Create(int? eqId = null)
        {
            ViewData["SportEquipment"] = new SelectList(_context.SportEquipment, "Id", "Name");
            Renting session = new Renting { UserId = CurrentUserId };
            if (eqId != null)
            {
                session.SportEquipmentId = eqId.Value;
            }
            session.End = DateTime.UtcNow;
            return View(session);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,SportEquipmentId,End")] Renting renting)
        {
            ViewData["SportEquipment"] = new SelectList(_context.SportEquipment, "Id", "Name");

            if (DateTime.Now.Date > renting.End.Date)
            {
                ModelState.AddModelError("End", "Data zakończenia wypożyczenia musi być późniejsza niż wczoraj");
            }
            renting.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            SportEquipment equipment = _context.SportEquipment.Include(s => s.Rentings).FirstOrDefault(x => x.Id == renting.SportEquipmentId);
            if(equipment.AvaibleUnits() == 0)
            {
                ModelState.AddModelError("SportEquipmentId", "Brak dostępnych sztuk");

            }
            if (ModelState.IsValid)
            {
                DateTime startDate = renting.Start;
                DateTime endDate = renting.End;
                renting.Start = DateTime.SpecifyKind(startDate, DateTimeKind.Utc);
                renting.End = DateTime.SpecifyKind(endDate, DateTimeKind.Utc);

                _context.Add(renting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(renting);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["SportEquipment"] = new SelectList(_context.SportEquipment.Include(x => x.Rentings).Where(r => r.AvaibleUnits() > 0), "Id", "Name");

            if (id == null)
            {
                return NotFound();
            }

            var renting = await _context.Renting.FindAsync(id);
            if (renting == null)
            {
                return NotFound();
            }
            if(renting.UserId !=  CurrentUserId)
            {
                throw new Exception();
            }
            return View(renting);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,SportEquipmentId,End")] Renting renting)
        {
            if (id != renting.Id)
            {
                return NotFound();
            }
            if (renting.UserId != CurrentUserId && !User.IsInRole("Admin") )
            {
                throw new Exception();
            }
            if (DateTime.Now.Date > renting.End.Date)
            {
                ModelState.AddModelError("End", "Data zakończenia wypożyczenia musi być późniejsza niż wczoraj");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(renting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentingExists(renting.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(renting);
        }

        // GET: Sessions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var renting = await _context.Renting.Include(x => x.SportEquipment)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (renting == null)
            {
                return NotFound();
            }
            if (renting.UserId != CurrentUserId && !User.IsInRole("Admin"))
            {
                throw new Exception();
            }
            return View(renting);
        }

        // POST: Sessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var renting = await _context.Renting.FindAsync(id);
            if (renting != null)
            {
                _context.Renting.Remove(renting);
            }
            if (renting.UserId != CurrentUserId && !User.IsInRole("Admin"))
            {
                throw new Exception();
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RentingExists(int id)
        {
            return _context.Renting.Any(e => e.Id == id);
        }
    }
}

SportEquipmentRent/Controllers/SportEquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportEquipmentRent.Data;
using SportEquipmentRent.Models;
using Microsoft.AspNetCore.Authorization;

namespace SportEquipmentRent.Controllers
{
    public class SportEquipmentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SportEquipmentController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.SportEquipment.Include(x => x.Rentings).ToListAsync());
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var SportEquipment = await _context.SportEquipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (SportEquipment == null)
            {
                return NotFound();
            }

            return View(SportEquipment);
        }
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Units,Name")] SportEquipment SportEquipment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(SportEquipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(SportEquipment);
        }

        [Authorize(Roles = "Admin")]

        // GET: SportEquipments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var SportEquipment = await _context.SportEquipment.FindAsync(id);
            if (SportEquipment == null)
            {
                return NotFound();
            }
            return View(SportEquipment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Units,Name")] SportEquipment SportEquipment)
        {
            if (id != SportEquipment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(SportEquipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SportEquipmentExists(SportEquipment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(SportEquipment);
        }


        // GET: SportEquipments/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var SportEquipment = await _context.SportEquipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (SportEquipment == null)
            {
                return NotFound();
            }

            return View(SportEquipment);
        }

        // POST: SportEquipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var SportEquipment = await _context.SportEquipment.FindAsync(id);
            if (SportEquipment != null)
            {
                _context.SportEquipment.Remove(SportEquipment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SportEquipmentExists(int id)
        {
            return _context.SportEquipment.Any(e => e.Id == id);
        }
    }
}

SportEquipmentRent/Views/SportEquipment/Create.cshtml
@model SportEquipmentRent.Models.SportEquipment

@{
    ViewData["Title"] = "Nowy sprzęt sportowy";
}

<h1>Nowy</h1>

<h4>Sprzęt sportowy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Units" class="control-label"></label>
                <input asp-for="Units" type="number" min="1" max="1000" class="form-control" />
                <span asp-validation-for="Units" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Utwórz" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary mt-2">Powrót do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportEquipmentRent/Views/SportEquipment/Delete.cshtml
@model SportEquipmentRent.Models.SportEquipment

@{
    ViewData["Title"] = "Usuwanie";
}

<h1>Usuń</h1>

<h3>Czy jesteś pewny, że chcesz usunąć sprzęt sportowy?</h3>
<div>
    <hr />
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Units)</th>
                <th>Liczba dostępnych sztuk</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.Name)</td>
                <td>@Html.DisplayFor(model => model.Units)</td>
                <td>@Model.AvaibleUnits()</td>
            </tr>
        </tbody>
    </table>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> 
        <a class="btn btn-warning" asp-action="Index">Powrót do listy</a>
    </form>
</div>

SportEquipmentRent/Views/SportEquipment/Details.cshtml
@model SportEquipmentRent.Models.SportEquipment

@{
    ViewData["Title"] = "Szczegóły";
}

<h1>Szczegóły</h1>

<div>
    <h4>Sprzęt sportowy</h4>
    <hr />
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Units)</th>
                <th>Liczba dostępnych sztuk</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.Name)</td>
                <td>@Html.DisplayFor(model => model.Units)</td>
                <td>@Model.AvaibleUnits()</td>
            </tr>
        </tbody>
    </table>
</div>

<div>
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.Id">Edytuj</a> 
    <a class="btn btn-outline-secondary" asp-action="Index">Powrót do listy</a>
</div>

SportEquipmentRent/Views/SportEquipment/Edit.cshtml
@model SportEquipmentRent.Models.SportEquipment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ExerciseType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Units" class="control-label"></label>
                <input asp-for="Units" type="number" min="1" max="1000" class="form-control" />
                <span asp-validation-for="Units" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportEquipmentRent/Views/SportEquipment/Index.cshtml
@model IEnumerable<SportEquipmentRent.Models.SportEquipment>

@{
    ViewData["Title"] = "Sprzęt sportowy do wypożyczenia";
}

<h1>Sprzęt sportowy do wypożyczenia</h1>

@if(User.IsInRole("Admin"))
{
    <p>
        <a class="btn btn-primary" asp-action="Create">Utwórz nowy</a>
    </p>
}

<table class="table table-hover table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Units)
            </th>
            <th>
                Dostępne sztuki
            </th>
            <th style="width: 20%;">Akcje</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Units)
                </td>
                <td>
                    @if (item.AvaibleUnits() > 0)
                    {
                        @item.AvaibleUnits()
                    }
                    else
                    {
                        <span class="text-muted">Brak dostępnych sztuk</span>
                    }
                </td>
                <td>
                    @if (User.IsInRole("Admin"))
                    {
                        <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id">
                            <i class="fas fa-edit"></i> Edytuj
                        </a>
                        <a class="btn btn-secondary btn-sm" asp-action="Details" asp-route-id="@item.Id">
                            <i class="fas fa-info-circle"></i> Szczegóły
                        </a>
                        <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">
                            <i class="fas fa-trash-alt"></i> Usuń
                        </a>
                    }
                    else if (User.IsInRole("User"))
                    {
                        if (item.AvaibleUnits() > 0)
                        {
                            <a class="btn btn-success btn-sm" asp-action="Create" asp-controller="Renting" asp-route-eqId="@item.Id">
                                <i class="fas fa-plus-circle"></i> Wypożycz
                            </a>
                        }
                        else
                        {
                            <span class="text-muted">Brak możliwości wypożyczenia</span>
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<style>
    .table {
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

        .table th, .table td {
            vertical-align: middle;
            text-align: center;
        }

    .table-hover tbody tr:hover {
        background-color: #f1f1f1;
    }

    .text-muted {
        color: #6c757d;
    }

    .btn {
        margin-right: 5px;
    }

</style>